pollInterval: 30  # seconds
backendURL: "http://localhost:8080"
sshTimeout: 10
retryAttempts: 3

devices:
  - host: "localhost"  # For testing, we'll monitor the local machine
    port: 22
    username: "maulikpuri"  # Your username
    password: "Mind@123"  # Leave empty if using SSH key
    sshKey: "/home/maulikpuri/.ssh/id_rsa"  # Absolute path to your SSH key

  # Add more devices as needed:
  # - host: "192.168.1.101"
  #   port: 22
  #   username: "monitor"
  #   password: "secret" 