zmq:
  backend_metrics: tcp://localhost:5556
  config_endpoint: tcp://*:5557
backendurl: http://localhost:8081
devices:
    - host: localhost
      port: 22
      username: maulikpuri
      password: Mind@123
      sshkey: /home/maulikpuri/.ssh/id_rsa
    - host: 10.20.40.103
      port: 8008
      username: dhyanesh
      password: Mind@123
      sshkey: ""
    - host: 10.20.40.107
      port: 22
      username: harekrushn
      password: Mind@123
      sshkey: ""
pollinterval: 3
retryattempts: 3
sshtimeout: 10
